"""HTML report generation for daily and weekly reports."""
from datetime import datetime, timezone, timedelta
from jinja2 import Environment, BaseLoader
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.database import AsyncSessionLocal
from app.models.user import User
from app.models.recommendation import Recommendation
from app.models.portfolio import Holding, Report
from app.services.portfolio_analyzer import PortfolioAnalyzer
from app.services.notifications import NotificationService

_portfolio_svc = PortfolioAnalyzer()
_notif_svc = NotificationService()

DAILY_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: auto; padding: 24px; color: #111; }
  h1 { color: #1a365d; border-bottom: 2px solid #3182ce; padding-bottom: 8px; }
  h2 { color: #2d3748; margin-top: 28px; }
  .summary-grid { display: flex; gap: 16px; flex-wrap: wrap; margin: 16px 0; }
  .card { background: #f7fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; min-width: 160px; flex: 1; }
  .card .value { font-size: 24px; font-weight: bold; }
  .card .label { color: #718096; font-size: 13px; }
  .positive { color: #16a34a; }
  .negative { color: #dc2626; }
  .neutral { color: #2563eb; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th { background: #2d3748; color: #fff; padding: 10px 12px; text-align: left; font-size: 13px; }
  td { padding: 9px 12px; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
  tr:hover td { background: #f7fafc; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: bold; color: #fff; }
  .BUY,.ADD_MORE { background: #16a34a; }
  .HOLD { background: #2563eb; }
  .PARTIAL_SELL { background: #d97706; }
  .SELL { background: #dc2626; }
  .AVOID { background: #6b7280; }
  .LOW { background: #16a34a; }
  .MEDIUM { background: #d97706; }
  .HIGH { background: #dc2626; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; color: #718096; font-size: 12px; }
</style>
</head>
<body>
<h1>📊 Daily Stock Market Report</h1>
<p style="color:#718096">{{ date }} | Generated by Stock Market Advisor</p>

<h2>Portfolio Summary</h2>
<div class="summary-grid">
  <div class="card">
    <div class="value">₹{{ "{:,.0f}".format(summary.total_current_value) }}</div>
    <div class="label">Current Value</div>
  </div>
  <div class="card">
    <div class="value {{ 'positive' if summary.total_pnl >= 0 else 'negative' }}">
      {{ '+' if summary.total_pnl >= 0 else '' }}₹{{ "{:,.0f}".format(summary.total_pnl) }}
    </div>
    <div class="label">Total P&L ({{ '+' if summary.total_pnl_pct >= 0 else '' }}{{ "%.2f"|format(summary.total_pnl_pct) }}%)</div>
  </div>
  <div class="card">
    <div class="value {{ 'positive' if summary.total_day_change >= 0 else 'negative' }}">
      {{ '+' if summary.total_day_change >= 0 else '' }}₹{{ "{:,.0f}".format(summary.total_day_change) }}
    </div>
    <div class="label">Today's Change</div>
  </div>
  <div class="card">
    <div class="value">{{ summary.holdings_count }}</div>
    <div class="label">Holdings</div>
  </div>
</div>

<h2>Today's Recommendations</h2>
{% if recommendations %}
<table>
  <tr><th>Stock</th><th>Signal</th><th>Risk</th><th>Price</th><th>Target</th><th>Confidence</th><th>Reason</th></tr>
  {% for r in recommendations %}
  <tr>
    <td><strong>{{ r.stock_symbol }}</strong><br><small>{{ r.stock_name }}</small></td>
    <td><span class="badge {{ r.signal }}">{{ r.signal.replace('_',' ') }}</span></td>
    <td><span class="badge {{ r.risk_level }}">{{ r.risk_level }}</span></td>
    <td>₹{{ "%.2f"|format(r.current_price) }}</td>
    <td>{{ '₹' + "%.2f"|format(r.target_price) if r.target_price else '–' }}</td>
    <td>{{ r.confidence_score|int }}%</td>
    <td>{{ r.reason[:120] }}...</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p style="color:#718096">No recommendations generated today.</p>
{% endif %}

{% if violations %}
<h2 style="color:#dc2626">⚠️ Portfolio Rule Violations</h2>
<ul>{% for v in violations %}<li>{{ v }}</li>{% endfor %}</ul>
{% endif %}

<div class="footer">
  <p><strong>Disclaimer:</strong> This is an AI-assisted recommendation. You are the final decision maker.
  Never invest more than 10% of your portfolio in a single stock or 25% in a single sector.
  Past performance is not indicative of future returns.</p>
</div>
</body>
</html>
"""


async def generate_daily_report_for_user(db: AsyncSession, user: User) -> str:
    from datetime import date
    today = datetime.now(timezone.utc).date()

    summary = await _portfolio_svc.get_summary(db, user.id)
    violations = await _portfolio_svc.get_violations(db, user.id)

    recs = (
        await db.execute(
            select(Recommendation).where(
                Recommendation.user_id == user.id,
                Recommendation.created_at >= datetime.combine(today, datetime.min.time()).replace(tzinfo=timezone.utc),
            ).order_by(Recommendation.confidence_score.desc())
        )
    ).scalars().all()

    env = Environment(loader=BaseLoader())
    tmpl = env.from_string(DAILY_REPORT_TEMPLATE)
    html = tmpl.render(
        date=today.strftime("%A, %d %B %Y"),
        summary=summary,
        recommendations=recs,
        violations=violations,
    )

    report = Report(
        user_id=user.id,
        report_type="daily",
        title=f"Daily Report – {today.strftime('%d %b %Y')}",
        content_html=html,
        report_date=datetime.now(timezone.utc),
    )
    db.add(report)
    await db.flush()
    return html


async def generate_daily_reports_for_all_users():
    async with AsyncSessionLocal() as db:
        users = (await db.execute(select(User).where(User.is_active == True))).scalars().all()
        for user in users:
            try:
                html = await generate_daily_report_for_user(db, user)
                await _notif_svc.send_daily_report(
                    html,
                    chat_id=user.telegram_chat_id,
                    email_to=user.email if user.email_alerts_enabled else None,
                )
            except Exception:
                pass
        await db.commit()


async def generate_weekly_reports_for_all_users():
    """Weekly report reuses daily template but covers last 7 days."""
    async with AsyncSessionLocal() as db:
        users = (await db.execute(select(User).where(User.is_active == True))).scalars().all()
        for user in users:
            try:
                html = await generate_daily_report_for_user(db, user)
                await _notif_svc.send_daily_report(
                    html,
                    chat_id=user.telegram_chat_id,
                    email_to=user.email if user.email_alerts_enabled else None,
                )
            except Exception:
                pass
        await db.commit()
